package com.onewallet.OneWallet.usecases.gateways.repo

import com.onewallet.OneWallet.usecases.user.RegisterUserByPhoneNumberUseCase

interface UserRepository: RegisterUserByPhoneNumberUseCase.UserRepository